[package]
name = "xevm"
version = "0.1.3"
edition = "2021"
description = "Tiny Ethereum virtual machine written in pure Rust"
license = "MIT"

[dependencies]
sha3 = "0.10.8"
anyhow = "1.0"
alloy_primitives = { package = "alloy", version = "0.9.2" }